version: "3"

services:
  app:
    container_name: product-service-app
    image: golang:1.17.2-stretch
    command: ["sh", "-c", "go mod download && go run server/main.go"]
    ports:
      - '2424:2424'
    environment:
      - PORT=2424
    working_dir: /app
    volumes:
      - ./:/app

  mysql:
    container_name: product-service-mysql
    image: mysql:8.0.27
    ports:
      - '3346:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - /microservice-volumes/product-service/mysql:/etc/mysql