version: "3"

services:
  app:
    container_name: product-service-app
    image: golang:1.17.2-stretch
    command: ["sh", "-c", "go mod download && go run main.go"]
    ports:
      - '2424:2424'
    environment:
      - PORT=2424
    working_dir: /app
    volumes:
      - ./:/app

  mysql:
    container_name: product-service-mysql
    image: mysql/mysql-server:8.0.27
    expose:
      - '3346'
    ports:
      - '3346:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product_service
      - MYSQL_USER=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - /microservice-volumes/product-service/mysql:/var/lib/mysql