// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/wisdommatt/ecommerce-microservice-product-service/grpc/proto"
)

// ProductServiceClient is an autogenerated mock type for the ProductServiceClient type
type ProductServiceClient struct {
	mock.Mock
}

// AddProduct provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) AddProduct(ctx context.Context, in *proto.NewProduct, opts ...grpc.CallOption) (*proto.Product, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.Product
	if rf, ok := ret.Get(0).(func(context.Context, *proto.NewProduct, ...grpc.CallOption) *proto.Product); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.NewProduct, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProduct provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) GetProduct(ctx context.Context, in *proto.GetProductInput, opts ...grpc.CallOption) (*proto.Product, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.Product
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetProductInput, ...grpc.CallOption) *proto.Product); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetProductInput, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
