// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeProductServiceServer is an autogenerated mock type for the UnsafeProductServiceServer type
type UnsafeProductServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedProductServiceServer provides a mock function with given fields:
func (_m *UnsafeProductServiceServer) mustEmbedUnimplementedProductServiceServer() {
	_m.Called()
}
